export const DASHBOARD = '/'
export const CREATE_MATCH = '/create-match'
export const PROFILE = '/profile'
export const ADD_USER = '/add-user'
export const USER_LIST = '/user-list'
export const MATCH_LIST = '/match-list'
